export const FETCH_ALL_USER_DATA = 'FETCH_ALL_USER_DATA';
export const FETCH_CURRENCY_DATA = 'FETCH_CURRENCY_DATA';
export const FETCH_ALL_CATEGORY_DATA = 'FETCH_ALL_CATEGORY_DATA';
export const FETCH_ALL_DEBTOR_DATA = 'FETCH_ALL_DEBTOR_DATA';
export const FETCH_ALL_EXPENSE_DATA = 'FETCH_ALL_EXPENSE_DATA';
export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
