import {
  // Navigation
  Home,
  BarChart3,
  CreditCard,
  Shapes,
  Settings,
  ArrowLeft,
  ChevronLeft,
  Menu,

  // Actions
  Plus,
  PlusCircle,
  Pencil,
  Trash2,
  Search,
  Calendar,
  CalendarDays,
  Filter,
  Download,
  Upload,
  Undo2,
  Check,
  CheckCircle,
  CheckCircle2,
  X,
  XCircle,
  MoreHorizontal,
  MoreVertical,
  RefreshCw,
  Eye,
  EyeOff,
  Copy,
  Share2,
  ExternalLink,

  // Finance
  Wallet,
  Landmark,
  Banknote,
  Receipt,
  PiggyBank,
  TrendingUp,
  TrendingDown,
  HandCoins,
  Coins,
  CircleDollarSign,
  BadgeDollarSign,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftRight,
  Calculator,

  // Food & Dining
  Utensils,
  UtensilsCrossed,
  Coffee,
  Wine,
  Beer,
  Pizza,
  Sandwich,
  Apple,
  Cherry,
  Soup,
  CookingPot,
  IceCream,
  Milk,
  Croissant,
  Salad,
  Beef,
  Fish,
  Egg,
  Cookie,
  Cake,
  CakeSlice,
  Candy,
  Popcorn,
  Grape,
  Banana,
  Carrot,
  Wheat,
  Leaf,
  LeafyGreen,
  Citrus,

  // Transport
  Car,
  CarFront,
  Bus,
  Train,
  TramFront,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Bike,
  Ship,
  Sailboat,
  Fuel,
  ParkingCircle,
  Navigation,
  MapPin,
  Map,
  Compass,
  Route,
  Truck,
  Ambulance,

  // Shopping
  ShoppingCart,
  ShoppingBag,
  Package,
  PackageOpen,
  Tag,
  Tags,
  Store,
  Shirt,
  Watch,
  Gem,
  Crown,
  Gift,
  Percent,
  BadgePercent,

  // Home & Utilities
  House,
  Building,
  Building2,
  Lightbulb,
  Zap,
  Droplet,
  Droplets,
  Flame,
  Wind,
  Wifi,
  WifiOff,
  Phone,
  Smartphone,
  Tv,
  Monitor,
  Laptop,
  TabletSmartphone,
  Gamepad2,
  Plug,
  Cable,
  Thermometer,
  AirVent,
  Bath,
  BedDouble,
  Sofa,
  Lamp,
  DoorOpen,
  Key,
  Lock,
  Unlock,
  ShieldCheck,
  Shield,

  // Health & Wellness
  Heart,
  HeartPulse,
  Activity,
  Pill,
  Stethoscope,
  Syringe,
  Bandage,
  Hospital,
  Cross,
  Brain,
  Dumbbell,
  PersonStanding,
  Footprints,
  Glasses,
  Ear,
  Hand,
  Smile,
  Frown,
  Meh,
  Moon,
  Sun,
  CloudSun,
  Umbrella,

  // Entertainment
  Music,
  Music2,
  Music4,
  Headphones,
  Film,
  Clapperboard,
  Camera,
  Image,
  Images,
  Palette,
  PaintBucket,
  Brush,
  Scissors,
  Sparkles,
  PartyPopper,
  Drama,
  Ticket,
  Dice5,
  Puzzle,
  Blocks,
  Book,
  BookOpen,
  BookMarked,
  Newspaper,
  Radio,
  Mic,
  Volume2,

  // Education & Work
  GraduationCap,
  School,
  Notebook,
  NotebookPen,
  FileText,
  Files,
  FolderOpen,
  Briefcase,
  BadgeCheck,
  Award,
  Trophy,
  Medal,
  Target,
  Lightbulb as LightbulbIdea,
  PenTool,
  Ruler,
  Presentation,

  // Pets & Animals
  PawPrint,
  Cat,
  Dog,
  Bird,
  Bug,
  Fish as FishAnimal,
  Rabbit,
  Squirrel,
  Snail,
  Turtle,

  // Nature & Outdoors
  Trees,
  TreeDeciduous,
  TreePine,
  Flower,
  Flower2,
  Sprout,
  Clover,
  Mountain,
  MountainSnow,
  Waves,
  Tent,
  FlameKindling,
  Flashlight,
  Backpack,
  Luggage,
  Globe,
  Globe2,
  Earth,
  Sunrise,
  Sunset,
  Cloud,
  CloudRain,
  Snowflake,
  Star,
  Sparkle,

  // Communication
  MessageCircle,
  MessageSquare,
  Mail,
  MailOpen,
  Send,
  AtSign,
  Bell,
  BellRing,
  Megaphone,

  // Social & Brands
  Users,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  Users2,
  Baby,
  Handshake,
  HeartHandshake,
  ThumbsUp,
  ThumbsDown,

  // Tech & Development
  Code,
  Terminal,
  Database,
  Server,
  HardDrive,
  Cpu,
  Usb,
  Bluetooth,
  Printer,
  Keyboard,
  ScanLine,
  QrCode,
  Fingerprint,
  Bot,
  CircuitBoard,

  // Miscellaneous
  Clock,
  Timer,
  Hourglass,
  AlarmClock,
  RotateCcw,
  RotateCw,
  Repeat,
  Infinity,
  Hash,
  Asterisk,
  CircleDot,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Flag,
  Bookmark,
  Pin,
  Paperclip,
  Link,
  Unlink,
  Anchor,
  Wrench,
  Hammer,
  Axe,
  Shovel,
  Paintbrush,
  Eraser,
  Scissors as ScissorsTool,
  Slice,
  Box,
  Archive,
  Inbox,
  Send as SendIcon,
  LogIn,
  LogOut,
  Power,
  ToggleLeft,
  ToggleRight,
  SlidersHorizontal,
  Settings2,
  Cog,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  Ban,
  ShieldAlert,
  Verified,
  BadgeInfo,
} from 'lucide-react-native';

export const ICON_REGISTRY = {
  // Navigation
  home: Home,
  'bar-chart-3': BarChart3,
  'credit-card': CreditCard,
  shapes: Shapes,
  settings: Settings,
  'arrow-left': ArrowLeft,
  'chevron-left': ChevronLeft,
  menu: Menu,

  // Actions
  plus: Plus,
  'plus-circle': PlusCircle,
  pencil: Pencil,
  'trash-2': Trash2,
  search: Search,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  filter: Filter,
  download: Download,
  upload: Upload,
  'undo-2': Undo2,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  x: X,
  'x-circle': XCircle,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'refresh-cw': RefreshCw,
  eye: Eye,
  'eye-off': EyeOff,
  copy: Copy,
  'share-2': Share2,
  'external-link': ExternalLink,

  // Finance
  wallet: Wallet,
  landmark: Landmark,
  banknote: Banknote,
  receipt: Receipt,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'hand-coins': HandCoins,
  coins: Coins,
  'circle-dollar-sign': CircleDollarSign,
  'badge-dollar-sign': BadgeDollarSign,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-left-right': ArrowLeftRight,
  calculator: Calculator,

  // Food & Dining
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  pizza: Pizza,
  sandwich: Sandwich,
  apple: Apple,
  cherry: Cherry,
  soup: Soup,
  'cooking-pot': CookingPot,
  'ice-cream': IceCream,
  milk: Milk,
  croissant: Croissant,
  salad: Salad,
  beef: Beef,
  fish: Fish,
  egg: Egg,
  cookie: Cookie,
  cake: Cake,
  'cake-slice': CakeSlice,
  candy: Candy,
  popcorn: Popcorn,
  grape: Grape,
  banana: Banana,
  carrot: Carrot,
  wheat: Wheat,
  leaf: Leaf,
  'leafy-green': LeafyGreen,
  citrus: Citrus,

  // Transport
  car: Car,
  'car-front': CarFront,
  bus: Bus,
  train: Train,
  'tram-front': TramFront,
  plane: Plane,
  'plane-takeoff': PlaneTakeoff,
  'plane-landing': PlaneLanding,
  bike: Bike,
  ship: Ship,
  sailboat: Sailboat,
  fuel: Fuel,
  'parking-circle': ParkingCircle,
  navigation: Navigation,
  'map-pin': MapPin,
  map: Map,
  compass: Compass,
  route: Route,
  truck: Truck,
  ambulance: Ambulance,

  // Shopping
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  package: Package,
  'package-open': PackageOpen,
  tag: Tag,
  tags: Tags,
  store: Store,
  shirt: Shirt,
  watch: Watch,
  gem: Gem,
  crown: Crown,
  gift: Gift,
  percent: Percent,
  'badge-percent': BadgePercent,

  // Home & Utilities
  house: House,
  building: Building,
  'building-2': Building2,
  lightbulb: Lightbulb,
  zap: Zap,
  droplet: Droplet,
  droplets: Droplets,
  flame: Flame,
  wind: Wind,
  wifi: Wifi,
  'wifi-off': WifiOff,
  phone: Phone,
  smartphone: Smartphone,
  tv: Tv,
  monitor: Monitor,
  laptop: Laptop,
  'tablet-smartphone': TabletSmartphone,
  'gamepad-2': Gamepad2,
  plug: Plug,
  cable: Cable,
  thermometer: Thermometer,
  'air-vent': AirVent,
  bath: Bath,
  'bed-double': BedDouble,
  sofa: Sofa,
  lamp: Lamp,
  'door-open': DoorOpen,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  'shield-check': ShieldCheck,
  shield: Shield,

  // Health & Wellness
  heart: Heart,
  'heart-pulse': HeartPulse,
  activity: Activity,
  pill: Pill,
  stethoscope: Stethoscope,
  syringe: Syringe,
  bandaid: Bandage,
  hospital: Hospital,
  cross: Cross,
  brain: Brain,
  dumbbell: Dumbbell,
  'person-standing': PersonStanding,
  footprints: Footprints,
  glasses: Glasses,
  ear: Ear,
  hand: Hand,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  moon: Moon,
  sun: Sun,
  'cloud-sun': CloudSun,
  umbrella: Umbrella,

  // Entertainment
  music: Music,
  'music-2': Music2,
  'music-4': Music4,
  headphones: Headphones,
  film: Film,
  clapperboard: Clapperboard,
  camera: Camera,
  image: Image,
  images: Images,
  palette: Palette,
  'paint-bucket': PaintBucket,
  brush: Brush,
  scissors: Scissors,
  sparkles: Sparkles,
  'party-popper': PartyPopper,
  drama: Drama,
  ticket: Ticket,
  'dice-5': Dice5,
  puzzle: Puzzle,
  blocks: Blocks,
  book: Book,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  newspaper: Newspaper,
  radio: Radio,
  mic: Mic,
  'volume-2': Volume2,

  // Education & Work
  'graduation-cap': GraduationCap,
  school: School,
  notebook: Notebook,
  'notebook-pen': NotebookPen,
  'file-text': FileText,
  files: Files,
  'folder-open': FolderOpen,
  briefcase: Briefcase,
  'badge-check': BadgeCheck,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  target: Target,
  'lightbulb-idea': LightbulbIdea,
  'pen-tool': PenTool,
  ruler: Ruler,
  presentation: Presentation,

  // Pets & Animals
  'paw-print': PawPrint,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  bug: Bug,
  'fish-animal': FishAnimal,
  rabbit: Rabbit,
  squirrel: Squirrel,
  snail: Snail,
  turtle: Turtle,

  // Nature & Outdoors
  trees: Trees,
  'tree-deciduous': TreeDeciduous,
  'tree-pine': TreePine,
  flower: Flower,
  'flower-2': Flower2,
  sprout: Sprout,
  clover: Clover,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  waves: Waves,
  tent: Tent,
  campfire: FlameKindling,
  flashlight: Flashlight,
  backpack: Backpack,
  luggage: Luggage,
  globe: Globe,
  'globe-2': Globe2,
  earth: Earth,
  sunrise: Sunrise,
  sunset: Sunset,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  snowflake: Snowflake,
  star: Star,
  sparkle: Sparkle,

  // Communication
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  mail: Mail,
  'mail-open': MailOpen,
  send: Send,
  'at-sign': AtSign,
  bell: Bell,
  'bell-ring': BellRing,
  megaphone: Megaphone,

  // Social & People
  users: Users,
  user: User,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'users-2': Users2,
  baby: Baby,
  handshake: Handshake,
  'heart-handshake': HeartHandshake,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,

  // Tech & Development
  code: Code,
  terminal: Terminal,
  database: Database,
  server: Server,
  'hard-drive': HardDrive,
  cpu: Cpu,
  usb: Usb,
  bluetooth: Bluetooth,
  printer: Printer,
  keyboard: Keyboard,
  'scan-line': ScanLine,
  'qr-code': QrCode,
  fingerprint: Fingerprint,
  bot: Bot,
  'circuit-board': CircuitBoard,

  // Miscellaneous
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  alarm: AlarmClock,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  repeat: Repeat,
  infinity: Infinity,
  hash: Hash,
  asterisk: Asterisk,
  'circle-dot': CircleDot,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  flag: Flag,
  bookmark: Bookmark,
  pin: Pin,
  paperclip: Paperclip,
  link: Link,
  unlink: Unlink,
  anchor: Anchor,
  wrench: Wrench,
  hammer: Hammer,
  axe: Axe,
  shovel: Shovel,
  paintbrush: Paintbrush,
  eraser: Eraser,
  'scissors-tool': ScissorsTool,
  slice: Slice,
  box: Box,
  archive: Archive,
  inbox: Inbox,
  'send-icon': SendIcon,
  'log-in': LogIn,
  'log-out': LogOut,
  power: Power,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  'sliders-horizontal': SlidersHorizontal,
  'settings-2': Settings2,
  cog: Cog,
  'help-circle': HelpCircle,
  info: Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  ban: Ban,
  'shield-alert': ShieldAlert,
  verified: Verified,
  'badge-info': BadgeInfo,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;

export const isValidIconName = (name: string): name is IconName => {
  return name in ICON_REGISTRY;
};

export {type LucideIcon} from 'lucide-react-native';
